import autoproof.Q10.Core.Operators.ObservedOps
import autoproof.Q10.Core.Operators.ProblemModel
import autoproof.Q10.Core.Operators.InnerSPD

set_option autoImplicit false

open scoped BigOperators Kronecker
open Matrix

namespace AutoProof
namespace Q10

noncomputable section

variable {n M r q : Nat}

/-- Matrix-free operator maps `0` to `0`. -/
theorem applyA_zero (P : Problem n M r q) :
    applyA P (0 : Matrix (Fin n) (Fin r) Real) = 0 := by
  simpa using
    (applyA_smul (P := P) (a := (0 : Real)) (W := (0 : Matrix (Fin n) (Fin r) Real)))

/-- Identity preconditioner (used to state unpreconditioned CG/Krylov facts). -/
def idPrecond {n r : Nat} : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real := fun R => R

/-- `applyA` as a linear endomorphism on matrix variables. -/
def applyALin (P : Problem n M r q) :
    Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real where
  toFun := applyA P
  map_add' := applyA_add P
  map_smul' := applyA_smul P

/-- Initial residual for a fixed initial guess. -/
def pcgR0 (P : Problem n M r q) (x0 : Matrix (Fin n) (Fin r) Real) :
    Matrix (Fin n) (Fin r) Real :=
  rhsMat P - applyA P x0

/-- Degree-`k` Krylov generating set `{r0, A r0, ..., A^k r0}`. -/
def krylovSet (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real) (k : Nat) :
    Set (Matrix (Fin n) (Fin r) Real) :=
  {v | ∃ i : Nat, i ≤ k ∧ v = ((applyALin P)^[i]) r0}

/-- Degree-`k` Krylov submodule generated by `r0`. -/
def krylovSubmodule (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real) (k : Nat) :
    Submodule Real (Matrix (Fin n) (Fin r) Real) :=
  Submodule.span Real (krylovSet P r0 k)

theorem krylovSubmodule_mono (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real) {k j : Nat}
    (hkj : k ≤ j) :
    krylovSubmodule P r0 k ≤ krylovSubmodule P r0 j := by
  exact Submodule.span_mono (by
    intro x hx
    rcases hx with ⟨i, hik, rfl⟩
    exact ⟨i, le_trans hik hkj, rfl⟩)

theorem applyA_mem_krylovSubmodule_succ
    (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real)
    {k : Nat} {v : Matrix (Fin n) (Fin r) Real}
    (hv : v ∈ krylovSubmodule P r0 k) :
    applyA P v ∈ krylovSubmodule P r0 (k + 1) := by
  change applyALin P v ∈ krylovSubmodule P r0 (k + 1)
  have hsubset :
      (applyALin P) '' (krylovSet P r0 k) ⊆ krylovSet P r0 (k + 1) := by
    intro y hy
    rcases hy with ⟨x, hx, rfl⟩
    rcases hx with ⟨i, hik, rfl⟩
    refine ⟨i + 1, Nat.succ_le_succ hik, ?_⟩
    simpa using (Function.iterate_succ_apply' (f := applyALin P) i r0).symm
  have hmap :
      Submodule.map (applyALin P) (krylovSubmodule P r0 k) ≤
        krylovSubmodule P r0 (k + 1) := by
    calc
      Submodule.map (applyALin P) (krylovSubmodule P r0 k)
          = Submodule.span Real ((applyALin P) '' (krylovSet P r0 k)) := by
              simp [krylovSubmodule]
      _ ≤ Submodule.span Real (krylovSet P r0 (k + 1)) := Submodule.span_mono hsubset
  exact hmap (by exact ⟨v, hv, rfl⟩)

/-- Ideal preconditioner (exact inverse action of the dense operator, in matrix coordinates). -/
noncomputable def idealMinv (P : Problem n M r q)
    (R : Matrix (Fin n) (Fin r) Real) : Matrix (Fin n) (Fin r) Real :=
  unvec ((denseMatrix P)⁻¹ *ᵥ R.vec)

theorem idealMinv_dense_correct (P : Problem n M r q)
    (hAinv : IsUnit (denseMatrix P).det)
    (R : Matrix (Fin n) (Fin r) Real) :
    applyDenseVec P.K P.Z P.Ω P.lam (idealMinv P R).vec = R.vec := by
  unfold idealMinv
  unfold applyDenseVec
  rw [vec_unvec]
  change denseMatrix P *ᵥ ((denseMatrix P)⁻¹ *ᵥ R.vec) = R.vec
  rw [Matrix.mulVec_mulVec, Matrix.mul_nonsing_inv (A := denseMatrix P) hAinv, Matrix.one_mulVec]

theorem applyA_idealMinv_eq (P : Problem n M r q)
    (hAinv : IsUnit (denseMatrix P).det)
    (R : Matrix (Fin n) (Fin r) Real) :
    applyA P (idealMinv P R) = R := by
  apply (Matrix.vec_inj).1
  calc
    (applyA P (idealMinv P R)).vec
        = applyDenseVec P.K P.Z P.Ω P.lam (idealMinv P R).vec := by
            simpa [applyA] using
              (applyDenseVec_eq_vec_applyMatrixFree (K := P.K) (Z := P.Z) (Ω := P.Ω)
                (lam := P.lam) (hK := P.hK) (W := idealMinv P R)).symm
    _ = R.vec := idealMinv_dense_correct (P := P) hAinv R

/-- PCG state in matrix coordinates. -/
structure PCGState (n rk : Nat) where
  x : Matrix (Fin n) (Fin rk) Real
  r : Matrix (Fin n) (Fin rk) Real
  z : Matrix (Fin n) (Fin rk) Real
  p : Matrix (Fin n) (Fin rk) Real

/-- PCG initialization with initial guess `x0`. -/
def pcgInit (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) : PCGState n r :=
  let r0 := rhsMat P - applyA P x0
  let z0 := Minv r0
  { x := x0, r := r0, z := z0, p := z0 }

/-- `A p` at the current PCG state. -/
def pcgAp (P : Problem n M r q) (st : PCGState n r) : Matrix (Fin n) (Fin r) Real :=
  applyA P st.p

/-- PCG step size `α`. -/
def pcgAlpha (P : Problem n M r q) (st : PCGState n r) : Real :=
  frobInner st.r st.z / frobInner st.p (pcgAp P st)

/-- Next PCG iterate `x' = x + α p`. -/
def pcgXNext (P : Problem n M r q) (st : PCGState n r) : Matrix (Fin n) (Fin r) Real :=
  st.x + pcgAlpha P st • st.p

/-- Next PCG residual `r' = r - α A p`. -/
def pcgRNext (P : Problem n M r q) (st : PCGState n r) : Matrix (Fin n) (Fin r) Real :=
  st.r - pcgAlpha P st • pcgAp P st

/-- Next PCG preconditioned residual `z' = M^{-1} r'`. -/
def pcgZNext (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (st : PCGState n r) : Matrix (Fin n) (Fin r) Real :=
  Minv (pcgRNext P st)

/-- PCG coefficient `β`. -/
def pcgBeta (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (st : PCGState n r) : Real :=
  frobInner (pcgRNext P st) (pcgZNext P Minv st) / frobInner st.r st.z

theorem pcgAlpha_den_pos_of_operatorSPD (P : Problem n M r q)
    (st : PCGState n r)
    (hSPD : operatorSPD P) (hp : st.p ≠ 0) :
    0 < frobInner st.p (pcgAp P st) := by
  simpa [pcgAp] using hSPD st.p hp

theorem pcgAlpha_den_ne_zero_of_operatorSPD (P : Problem n M r q)
    (st : PCGState n r)
    (hSPD : operatorSPD P) (hp : st.p ≠ 0) :
    frobInner st.p (pcgAp P st) ≠ 0 :=
  ne_of_gt (pcgAlpha_den_pos_of_operatorSPD (P := P) (st := st) hSPD hp)

/-- Next PCG search direction `p' = z' + β p`. -/
def pcgPNext (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (st : PCGState n r) : Matrix (Fin n) (Fin r) Real :=
  pcgZNext P Minv st + pcgBeta P Minv st • st.p

/-- One PCG step. -/
def pcgStep (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (st : PCGState n r) : PCGState n r :=
  { x := pcgXNext P st
    r := pcgRNext P st
    z := pcgZNext P Minv st
    p := pcgPNext P Minv st }

/-- Run PCG for `iters` steps from initial guess `x0`. -/
def pcgRun (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) : Nat → PCGState n r
  | 0 => pcgInit P Minv x0
  | k + 1 => pcgStep P Minv (pcgRun P Minv x0 k)

theorem pcgInit_id_r_eq_r0 (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    (pcgInit P idPrecond x0).r = pcgR0 P x0 := by
  simp [pcgInit, idPrecond, pcgR0]

theorem pcgInit_id_p_eq_r0 (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    (pcgInit P idPrecond x0).p = pcgR0 P x0 := by
  simp [pcgInit, idPrecond, pcgR0]

theorem pcgRNext_mem_krylovSubmodule_succ_of_mem
    (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real)
    {k : Nat} {st : PCGState n r}
    (hr : st.r ∈ krylovSubmodule P r0 k)
    (hp : st.p ∈ krylovSubmodule P r0 k) :
    pcgRNext P st ∈ krylovSubmodule P r0 (k + 1) := by
  have hrLift : st.r ∈ krylovSubmodule P r0 (k + 1) :=
    krylovSubmodule_mono (P := P) (r0 := r0) (hkj := Nat.le_succ k) hr
  have hAp : applyA P st.p ∈ krylovSubmodule P r0 (k + 1) :=
    applyA_mem_krylovSubmodule_succ (P := P) (r0 := r0) hp
  exact Submodule.sub_mem (krylovSubmodule P r0 (k + 1)) hrLift
    (Submodule.smul_mem (krylovSubmodule P r0 (k + 1)) (pcgAlpha P st) hAp)

theorem pcgPNext_id_mem_krylovSubmodule_succ_of_mem
    (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real)
    {k : Nat} {st : PCGState n r}
    (hr : st.r ∈ krylovSubmodule P r0 k)
    (hp : st.p ∈ krylovSubmodule P r0 k) :
    pcgPNext P idPrecond st ∈ krylovSubmodule P r0 (k + 1) := by
  have hrNext : pcgRNext P st ∈ krylovSubmodule P r0 (k + 1) :=
    pcgRNext_mem_krylovSubmodule_succ_of_mem (P := P) (r0 := r0) (hr := hr) (hp := hp)
  have hpLift : st.p ∈ krylovSubmodule P r0 (k + 1) :=
    krylovSubmodule_mono (P := P) (r0 := r0) (hkj := Nat.le_succ k) hp
  simpa [pcgPNext, pcgZNext, idPrecond] using
    Submodule.add_mem (krylovSubmodule P r0 (k + 1)) hrNext
      (Submodule.smul_mem (krylovSubmodule P r0 (k + 1)) (pcgBeta P idPrecond st) hpLift)

/-- Algorithmic Krylov-subspace statement for unpreconditioned CG:
at step `k`, both the residual and search direction lie in the degree-`k` Krylov submodule
generated by the initial residual. -/
theorem pcgRun_id_residual_search_mem_krylovSubmodule
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat,
      (pcgRun P idPrecond x0 k).r ∈ krylovSubmodule P (pcgR0 P x0) k ∧
      (pcgRun P idPrecond x0 k).p ∈ krylovSubmodule P (pcgR0 P x0) k := by
  intro k
  induction k with
  | zero =>
      refine ⟨?_, ?_⟩
      · have hr0 : (pcgInit P idPrecond x0).r = pcgR0 P x0 := pcgInit_id_r_eq_r0 (P := P) (x0 := x0)
        rw [pcgRun, hr0]
        exact Submodule.subset_span ⟨0, le_rfl, by simp⟩
      · have hp0 : (pcgInit P idPrecond x0).p = pcgR0 P x0 := pcgInit_id_p_eq_r0 (P := P) (x0 := x0)
        rw [pcgRun, hp0]
        exact Submodule.subset_span ⟨0, le_rfl, by simp⟩
  | succ k ih =>
      let st : PCGState n r := pcgRun P idPrecond x0 k
      have hrk : st.r ∈ krylovSubmodule P (pcgR0 P x0) k := by simpa [st] using ih.1
      have hpk : st.p ∈ krylovSubmodule P (pcgR0 P x0) k := by simpa [st] using ih.2
      have hrNext :
          pcgRNext P st ∈ krylovSubmodule P (pcgR0 P x0) (k + 1) :=
        pcgRNext_mem_krylovSubmodule_succ_of_mem
          (P := P) (r0 := pcgR0 P x0) (hr := hrk) (hp := hpk)
      have hpNext :
          pcgPNext P idPrecond st ∈ krylovSubmodule P (pcgR0 P x0) (k + 1) :=
        pcgPNext_id_mem_krylovSubmodule_succ_of_mem
          (P := P) (r0 := pcgR0 P x0) (hr := hrk) (hp := hpk)
      refine ⟨?_, ?_⟩
      · simpa [pcgRun, pcgStep, st] using hrNext
      · simpa [pcgRun, pcgStep, st] using hpNext

/-- Polynomial action of a linear endomorphism on a seed vector. -/
def polyApplyLin {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (p : Polynomial Real) (v : V) : V :=
  (Polynomial.aeval A p) v

theorem polyApplyLin_X_pow {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v : V) (i : Nat) :
    polyApplyLin A (Polynomial.X ^ i) v = (⇑A)^[i] v := by
  simpa [polyApplyLin, Module.End.pow_apply]

/-- `denseMatrix` as a linear endomorphism on vectorized coordinates. -/
def denseVecLin (P : Problem n M r q) :
    Module.End Real (Fin r × Fin n → Real) :=
  Matrix.toLinAlgEquiv' (denseMatrix P)

@[simp] theorem denseVecLin_apply (P : Problem n M r q) (x : Fin r × Fin n → Real) :
    denseVecLin P x = denseMatrix P *ᵥ x := by
  simpa [denseVecLin] using Matrix.toLinAlgEquiv'_apply (M := denseMatrix P) (v := x)

/-- `applyALin` matches `denseVecLin` under `vec`. -/
theorem applyALin_vec_eq_denseVecLin
    (P : Problem n M r q)
    (X : Matrix (Fin n) (Fin r) Real) :
    (applyALin P X).vec = denseVecLin P X.vec := by
  simpa [applyALin] using applyA_vec (P := P) (W := X)

/-- Iterates of `applyALin` match iterates of `denseVecLin` under `vec`. -/
theorem applyALin_iterate_vec_eq_denseVecLin_iterate
    (P : Problem n M r q)
    (k : Nat)
    (X : Matrix (Fin n) (Fin r) Real) :
    (((applyALin P)^[k]) X).vec = (((denseVecLin P)^[k]) X.vec) := by
  induction k with
  | zero =>
      simp
  | succ k ih =>
      calc
        (((applyALin P)^[k + 1]) X).vec
            = (applyALin P ((((applyALin P)^[k]) X))).vec := by
                simp [Function.iterate_succ_apply']
        _ = denseVecLin P ((((applyALin P)^[k]) X).vec) :=
              applyALin_vec_eq_denseVecLin (P := P) ((((applyALin P)^[k]) X))
        _ = denseVecLin P ((((denseVecLin P)^[k]) X.vec) : Fin r × Fin n → Real) := by
              rw [ih]
        _ = (((denseVecLin P)^[k + 1]) X.vec) := by
              simp [Function.iterate_succ_apply']

/-- Polynomial action of `applyALin` matches polynomial action of `denseVecLin`
under `vec`. -/
theorem polyApplyLin_applyALin_vec_eq_polyApplyLin_denseVecLin
    (P : Problem n M r q)
    (p : Polynomial Real)
    (X : Matrix (Fin n) (Fin r) Real) :
    (polyApplyLin (applyALin P) p X).vec
      = polyApplyLin (denseVecLin P) p X.vec := by
  induction p using Polynomial.induction_on with
  | C a =>
      simp [polyApplyLin]
  | add p q ihp ihq =>
      simpa [polyApplyLin] using congrArg₂ (fun u v => u + v) ihp ihq
  | monomial m a _ =>
      have hRecurrence :
          (applyALin P ((((applyALin P)^[m]) X))).vec
            = denseVecLin P ((((denseVecLin P)^[m]) X.vec) : Fin r × Fin n → Real) := by
        calc
          (applyALin P ((((applyALin P)^[m]) X))).vec
              = denseVecLin P ((((applyALin P)^[m]) X).vec) :=
                  applyALin_vec_eq_denseVecLin (P := P) ((((applyALin P)^[m]) X))
          _ = denseVecLin P ((((denseVecLin P)^[m]) X.vec) : Fin r × Fin n → Real) := by
                rw [applyALin_iterate_vec_eq_denseVecLin_iterate (P := P) (k := m) (X := X)]
      have hSmul :
          a • (applyALin P ((((applyALin P)^[m]) X))).vec
            = a • denseVecLin P ((((denseVecLin P)^[m]) X.vec) : Fin r × Fin n → Real) :=
        congrArg (fun t => a • t) hRecurrence
      simpa [polyApplyLin, Module.End.pow_apply, Function.iterate_succ_apply'] using hSmul

/-- Every vector in a degree-`k` Krylov submodule has an explicit polynomial form `p(A) r0`. -/
theorem mem_krylovSubmodule_exists_poly
    (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real)
    {k : Nat} {v : Matrix (Fin n) (Fin r) Real}
    (hv : v ∈ krylovSubmodule P r0 k) :
    ∃ p : Polynomial Real, v = polyApplyLin (applyALin P) p r0 := by
  refine Submodule.span_induction
    (s := krylovSet P r0 k)
    (p := fun x _ => ∃ p : Polynomial Real, x = polyApplyLin (applyALin P) p r0)
    ?hmem ?hzero ?hadd ?hsmul hv
  · intro x hx
    rcases hx with ⟨i, hik, rfl⟩
    refine ⟨Polynomial.X ^ i, ?_⟩
    simpa using (polyApplyLin_X_pow (A := applyALin P) (v := r0) (i := i)).symm
  · exact ⟨0, by simp [polyApplyLin]⟩
  · intro x y hx hy hxP hyP
    rcases hxP with ⟨px, rfl⟩
    rcases hyP with ⟨py, rfl⟩
    refine ⟨px + py, ?_⟩
    simp [polyApplyLin]
  · intro a x hx hxP
    rcases hxP with ⟨px, rfl⟩
    refine ⟨Polynomial.C a * px, ?_⟩
    simp [polyApplyLin, Module.End.mul_apply]

/-- Degree-refined polynomial representation inside a degree-`k` Krylov submodule. -/
theorem mem_krylovSubmodule_exists_poly_deg
    (P : Problem n M r q)
    (r0 : Matrix (Fin n) (Fin r) Real)
    {k : Nat} {v : Matrix (Fin n) (Fin r) Real}
    (hv : v ∈ krylovSubmodule P r0 k) :
    ∃ p : Polynomial Real,
      v = polyApplyLin (applyALin P) p r0 ∧ p.natDegree ≤ k := by
  refine Submodule.span_induction
    (s := krylovSet P r0 k)
    (p := fun x _ => ∃ p : Polynomial Real,
      x = polyApplyLin (applyALin P) p r0 ∧ p.natDegree ≤ k)
    ?hmem ?hzero ?hadd ?hsmul hv
  · intro x hx
    rcases hx with ⟨i, hik, rfl⟩
    refine ⟨Polynomial.X ^ i, ?_, ?_⟩
    · simpa using (polyApplyLin_X_pow (A := applyALin P) (v := r0) (i := i)).symm
    · simpa [Polynomial.natDegree_X_pow] using hik
  · refine ⟨0, ?_, ?_⟩
    · simp [polyApplyLin]
    · simp
  · intro x y hx hy hxP hyP
    rcases hxP with ⟨px, rfl, hdx⟩
    rcases hyP with ⟨py, rfl, hdy⟩
    refine ⟨px + py, ?_, ?_⟩
    · simp [polyApplyLin]
    · exact le_trans (Polynomial.natDegree_add_le px py) (max_le hdx hdy)
  · intro a x hx hxP
    rcases hxP with ⟨px, rfl, hdx⟩
    refine ⟨Polynomial.C a * px, ?_, ?_⟩
    · simp [polyApplyLin, Module.End.mul_apply]
    · exact le_trans (Polynomial.natDegree_C_mul_le a px) hdx

/-- Algorithmic polynomial-Krylov form for unpreconditioned CG:
both residual and search direction of `pcgRun` are explicit `p(A) r0` vectors. -/
theorem pcgRun_id_residual_search_poly_representation
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, ∃ pr pp : Polynomial Real,
      (pcgRun P idPrecond x0 k).r = polyApplyLin (applyALin P) pr (pcgR0 P x0) ∧
      (pcgRun P idPrecond x0 k).p = polyApplyLin (applyALin P) pp (pcgR0 P x0) := by
  intro k
  have hkry := pcgRun_id_residual_search_mem_krylovSubmodule (P := P) (x0 := x0) k
  rcases mem_krylovSubmodule_exists_poly
      (P := P) (r0 := pcgR0 P x0) (v := (pcgRun P idPrecond x0 k).r) hkry.1 with
    ⟨pr, hpr⟩
  rcases mem_krylovSubmodule_exists_poly
      (P := P) (r0 := pcgR0 P x0) (v := (pcgRun P idPrecond x0 k).p) hkry.2 with
    ⟨pp, hpp⟩
  exact ⟨pr, pp, hpr, hpp⟩

/-- Degree-refined algorithmic polynomial-Krylov form for unpreconditioned CG:
at iteration `k`, both residual/search polynomials can be chosen with degree at most `k`. -/
theorem pcgRun_id_residual_search_poly_representation_deg
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, ∃ pr pp : Polynomial Real,
      (pcgRun P idPrecond x0 k).r = polyApplyLin (applyALin P) pr (pcgR0 P x0) ∧
      pr.natDegree ≤ k ∧
      (pcgRun P idPrecond x0 k).p = polyApplyLin (applyALin P) pp (pcgR0 P x0) ∧
      pp.natDegree ≤ k := by
  intro k
  have hkry := pcgRun_id_residual_search_mem_krylovSubmodule (P := P) (x0 := x0) k
  rcases mem_krylovSubmodule_exists_poly_deg
      (P := P) (r0 := pcgR0 P x0) (v := (pcgRun P idPrecond x0 k).r) hkry.1 with
    ⟨pr, hpr, hdegR⟩
  rcases mem_krylovSubmodule_exists_poly_deg
      (P := P) (r0 := pcgR0 P x0) (v := (pcgRun P idPrecond x0 k).p) hkry.2 with
    ⟨pp, hpp, hdegP⟩
  exact ⟨pr, pp, hpr, hdegR, hpp, hdegP⟩

/-- Recursive polynomial construction from the `pcgRun` update equations
for unpreconditioned CG (`Minv = id`): residual/search vectors are generated as
`p_k(A) r0` / `q_k(A) r0`, and `p_k(0)=1` for every `k`. -/
theorem pcgRun_id_residual_search_poly_evalZero
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, ∃ pr pp : Polynomial Real,
      (pcgRun P idPrecond x0 k).r = polyApplyLin (applyALin P) pr (pcgR0 P x0) ∧
      (pcgRun P idPrecond x0 k).p = polyApplyLin (applyALin P) pp (pcgR0 P x0) ∧
      pr.eval 0 = 1 := by
  intro k
  induction k with
  | zero =>
      refine ⟨1, 1, ?_, ?_, ?_⟩
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin]
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, idPrecond]
      · simp
  | succ k ih =>
      rcases ih with ⟨pr, pp, hpr, hpp, hpr0⟩
      let st : PCGState n r := pcgRun P idPrecond x0 k
      let pr' : Polynomial Real := pr - Polynomial.C (pcgAlpha P st) * Polynomial.X * pp
      let pp' : Polynomial Real := pr' + Polynomial.C (pcgBeta P idPrecond st) * pp
      have hst_r : st.r = polyApplyLin (applyALin P) pr (pcgR0 P x0) := by
        simpa [st] using hpr
      have hst_p : st.p = polyApplyLin (applyALin P) pp (pcgR0 P x0) := by
        simpa [st] using hpp
      have hAp :
          applyA P st.p
            = polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
        calc
          applyA P st.p
              = applyALin P st.p := rfl
          _ = applyALin P (polyApplyLin (applyALin P) pp (pcgR0 P x0)) := by simpa [hst_p]
          _ = polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
                symm
                simp [polyApplyLin, Module.End.mul_apply]
      have hrNext :
          pcgRNext P st = polyApplyLin (applyALin P) pr' (pcgR0 P x0) := by
        unfold pr'
        calc
          pcgRNext P st
              = st.r - pcgAlpha P st • applyA P st.p := by rfl
          _ = polyApplyLin (applyALin P) pr (pcgR0 P x0)
                - pcgAlpha P st •
                    polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [hst_r, hAp]
          _ = polyApplyLin (applyALin P) pr (pcgR0 P x0)
                - polyApplyLin (applyALin P)
                    (Polynomial.C (pcgAlpha P st) * Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin, Module.End.mul_apply]
          _ = polyApplyLin (applyALin P)
                (pr - Polynomial.C (pcgAlpha P st) * Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin]
      have hpNext :
          pcgPNext P idPrecond st = polyApplyLin (applyALin P) pp' (pcgR0 P x0) := by
        unfold pp'
        calc
          pcgPNext P idPrecond st
              = pcgRNext P st + pcgBeta P idPrecond st • st.p := by
                  simp [pcgPNext, pcgZNext, idPrecond]
          _ = polyApplyLin (applyALin P) pr' (pcgR0 P x0)
                + pcgBeta P idPrecond st •
                    polyApplyLin (applyALin P) pp (pcgR0 P x0) := by
                  simp [hrNext, hst_p]
          _ = polyApplyLin (applyALin P) pr' (pcgR0 P x0)
                + polyApplyLin (applyALin P)
                    (Polynomial.C (pcgBeta P idPrecond st) * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin, Module.End.mul_apply]
          _ = polyApplyLin (applyALin P)
                (pr' + Polynomial.C (pcgBeta P idPrecond st) * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin]
      have hpr0' : pr'.eval 0 = 1 := by
        simp [pr', hpr0]
      refine ⟨pr', pp', ?_, ?_, hpr0'⟩
      · simpa [pcgRun, pcgStep, st] using hrNext
      · simpa [pcgRun, pcgStep, st] using hpNext

/-- Degree-refined recursive polynomial construction for unpreconditioned CG:
at step `k`, the residual polynomial has `eval 0 = 1` and both residual/search
polynomial degrees are bounded by `k`. -/
theorem pcgRun_id_residual_search_poly_evalZero_deg
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, ∃ pr pp : Polynomial Real,
      (pcgRun P idPrecond x0 k).r = polyApplyLin (applyALin P) pr (pcgR0 P x0) ∧
      (pcgRun P idPrecond x0 k).p = polyApplyLin (applyALin P) pp (pcgR0 P x0) ∧
      pr.eval 0 = 1 ∧
      pr.natDegree ≤ k ∧ pp.natDegree ≤ k := by
  intro k
  induction k with
  | zero =>
      refine ⟨1, 1, ?_, ?_, ?_, ?_, ?_⟩
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin]
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, idPrecond]
      · simp
      · simp
      · simp
  | succ k ih =>
      rcases ih with ⟨pr, pp, hpr, hpp, hpr0, hdegR, hdegP⟩
      let st : PCGState n r := pcgRun P idPrecond x0 k
      let pr' : Polynomial Real := pr - Polynomial.C (pcgAlpha P st) * Polynomial.X * pp
      let pp' : Polynomial Real := pr' + Polynomial.C (pcgBeta P idPrecond st) * pp
      have hst_r : st.r = polyApplyLin (applyALin P) pr (pcgR0 P x0) := by
        simpa [st] using hpr
      have hst_p : st.p = polyApplyLin (applyALin P) pp (pcgR0 P x0) := by
        simpa [st] using hpp
      have hAp :
          applyA P st.p
            = polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
        calc
          applyA P st.p
              = applyALin P st.p := rfl
          _ = applyALin P (polyApplyLin (applyALin P) pp (pcgR0 P x0)) := by simpa [hst_p]
          _ = polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
                symm
                simp [polyApplyLin, Module.End.mul_apply]
      have hrNext :
          pcgRNext P st = polyApplyLin (applyALin P) pr' (pcgR0 P x0) := by
        unfold pr'
        calc
          pcgRNext P st
              = st.r - pcgAlpha P st • applyA P st.p := by rfl
          _ = polyApplyLin (applyALin P) pr (pcgR0 P x0)
                - pcgAlpha P st •
                    polyApplyLin (applyALin P) (Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [hst_r, hAp]
          _ = polyApplyLin (applyALin P) pr (pcgR0 P x0)
                - polyApplyLin (applyALin P)
                    (Polynomial.C (pcgAlpha P st) * Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin, Module.End.mul_apply]
          _ = polyApplyLin (applyALin P)
                (pr - Polynomial.C (pcgAlpha P st) * Polynomial.X * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin]
      have hpNext :
          pcgPNext P idPrecond st = polyApplyLin (applyALin P) pp' (pcgR0 P x0) := by
        unfold pp'
        calc
          pcgPNext P idPrecond st
              = pcgRNext P st + pcgBeta P idPrecond st • st.p := by
                  simp [pcgPNext, pcgZNext, idPrecond]
          _ = polyApplyLin (applyALin P) pr' (pcgR0 P x0)
                + pcgBeta P idPrecond st •
                    polyApplyLin (applyALin P) pp (pcgR0 P x0) := by
                  simp [hrNext, hst_p]
          _ = polyApplyLin (applyALin P) pr' (pcgR0 P x0)
                + polyApplyLin (applyALin P)
                    (Polynomial.C (pcgBeta P idPrecond st) * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin, Module.End.mul_apply]
          _ = polyApplyLin (applyALin P)
                (pr' + Polynomial.C (pcgBeta P idPrecond st) * pp) (pcgR0 P x0) := by
                  simp [polyApplyLin]
      have hpr0' : pr'.eval 0 = 1 := by
        simp [pr', hpr0]
      have hdegCX : (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree ≤ 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree
              ≤ (Polynomial.C (pcgAlpha P st)).natDegree + Polynomial.X.natDegree :=
                Polynomial.natDegree_mul_le
          _ = 0 + 1 := by
                simp [Polynomial.natDegree_C, Polynomial.natDegree_X]
          _ = 1 := by simp
      have hdegCXpp : (Polynomial.C (pcgAlpha P st) * Polynomial.X * pp).natDegree ≤ k + 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pp).natDegree
              ≤ (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree + pp.natDegree :=
                Polynomial.natDegree_mul_le
          _ ≤ 1 + pp.natDegree := Nat.add_le_add_right hdegCX pp.natDegree
          _ ≤ 1 + k := Nat.add_le_add_left hdegP 1
          _ = k + 1 := by simp [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc]
      have hdegPr' : pr'.natDegree ≤ k + 1 := by
        unfold pr'
        calc
          (pr - Polynomial.C (pcgAlpha P st) * Polynomial.X * pp).natDegree
              ≤ max pr.natDegree (Polynomial.C (pcgAlpha P st) * Polynomial.X * pp).natDegree :=
                Polynomial.natDegree_sub_le _ _
          _ ≤ k + 1 := max_le (le_trans hdegR (Nat.le_succ k)) hdegCXpp
      have hdegCpp : (Polynomial.C (pcgBeta P idPrecond st) * pp).natDegree ≤ k + 1 := by
        calc
          (Polynomial.C (pcgBeta P idPrecond st) * pp).natDegree
              ≤ pp.natDegree := Polynomial.natDegree_C_mul_le _ _
          _ ≤ k + 1 := le_trans hdegP (Nat.le_succ k)
      have hdegPp' : pp'.natDegree ≤ k + 1 := by
        unfold pp'
        calc
          (pr' + Polynomial.C (pcgBeta P idPrecond st) * pp).natDegree
              ≤ max pr'.natDegree (Polynomial.C (pcgBeta P idPrecond st) * pp).natDegree :=
                Polynomial.natDegree_add_le _ _
          _ ≤ k + 1 := max_le hdegPr' hdegCpp
      refine ⟨pr', pp', ?_, ?_, hpr0', hdegPr', hdegPp'⟩
      · simpa [pcgRun, pcgStep, st] using hrNext
      · simpa [pcgRun, pcgStep, st] using hpNext

/-- Canonical residual/search polynomial recursion driven by the concrete
`pcgRun` scalars (`alpha_k`, `beta_k`) under identity preconditioning. -/
def pcgResidualSearchPolyRec
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) : Nat → (Polynomial Real × Polynomial Real)
  | 0 => (1, 1)
  | k + 1 =>
      let st : PCGState n r := pcgRun P idPrecond x0 k
      let prev := pcgResidualSearchPolyRec P x0 k
      let prk := prev.1
      let ppk := prev.2
      let prNext := prk - Polynomial.C (pcgAlpha P st) * Polynomial.X * ppk
      let ppNext := prNext + Polynomial.C (pcgBeta P idPrecond st) * ppk
      (prNext, ppNext)

def pcgResidualPolyRec
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) (k : Nat) : Polynomial Real :=
  (pcgResidualSearchPolyRec P x0 k).1

def pcgSearchPolyRec
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) (k : Nat) : Polynomial Real :=
  (pcgResidualSearchPolyRec P x0 k).2

theorem pcgRun_id_residual_search_polyRec_correct
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat,
      (pcgRun P idPrecond x0 k).r
        = polyApplyLin (applyALin P) (pcgResidualPolyRec P x0 k) (pcgR0 P x0) ∧
      (pcgRun P idPrecond x0 k).p
        = polyApplyLin (applyALin P) (pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
  intro k
  induction k with
  | zero =>
      refine ⟨?_, ?_⟩
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, pcgResidualPolyRec, pcgResidualSearchPolyRec]
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, idPrecond, pcgSearchPolyRec, pcgResidualSearchPolyRec]
  | succ k ih =>
      let st : PCGState n r := pcgRun P idPrecond x0 k
      have hrk : st.r
          = polyApplyLin (applyALin P) (pcgResidualPolyRec P x0 k) (pcgR0 P x0) := by
        simpa [st] using ih.1
      have hpk : st.p
          = polyApplyLin (applyALin P) (pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
        simpa [st] using ih.2
      have hApk :
          pcgAp P st
            = polyApplyLin (applyALin P)
                (Polynomial.X * pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
        calc
          pcgAp P st = applyALin P st.p := rfl
          _ = applyALin P
                (polyApplyLin (applyALin P) (pcgSearchPolyRec P x0 k) (pcgR0 P x0)) := by
                simpa [hpk]
          _ = polyApplyLin (applyALin P)
                (Polynomial.X * pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
                simp [polyApplyLin, Module.End.mul_apply]
      have hrNext :
          (pcgRun P idPrecond x0 (k + 1)).r
            = polyApplyLin (applyALin P)
                (pcgResidualPolyRec P x0 (k + 1)) (pcgR0 P x0) := by
        calc
          (pcgRun P idPrecond x0 (k + 1)).r
              = pcgRNext P st := by simp [pcgRun, pcgStep, st]
          _ = st.r - pcgAlpha P st • pcgAp P st := by rfl
          _ = polyApplyLin (applyALin P) (pcgResidualPolyRec P x0 k) (pcgR0 P x0)
                - pcgAlpha P st •
                    polyApplyLin (applyALin P)
                      (Polynomial.X * pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
                simp [hrk, hApk]
          _ = polyApplyLin (applyALin P)
                (pcgResidualPolyRec P x0 k
                  - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k)
                (pcgR0 P x0) := by
                simp [polyApplyLin, Module.End.mul_apply, mul_assoc]
          _ = polyApplyLin (applyALin P)
                (pcgResidualPolyRec P x0 (k + 1)) (pcgR0 P x0) := by
                simp [pcgResidualPolyRec, pcgSearchPolyRec, pcgResidualSearchPolyRec, st]
      have hRNextEq :
          pcgRNext P st
            = polyApplyLin (applyALin P)
                (pcgResidualPolyRec P x0 (k + 1)) (pcgR0 P x0) := by
        simpa [pcgRun, pcgStep, st] using hrNext
      have hpNext :
          (pcgRun P idPrecond x0 (k + 1)).p
            = polyApplyLin (applyALin P)
                (pcgSearchPolyRec P x0 (k + 1)) (pcgR0 P x0) := by
        calc
          (pcgRun P idPrecond x0 (k + 1)).p
              = pcgPNext P idPrecond st := by simp [pcgRun, pcgStep, st]
          _ = pcgRNext P st + pcgBeta P idPrecond st • st.p := by
                simp [pcgPNext, pcgZNext, idPrecond]
          _ = polyApplyLin (applyALin P) (pcgResidualPolyRec P x0 (k + 1)) (pcgR0 P x0)
                + pcgBeta P idPrecond st •
                    polyApplyLin (applyALin P) (pcgSearchPolyRec P x0 k) (pcgR0 P x0) := by
                simp [hRNextEq, hpk]
          _ = polyApplyLin (applyALin P)
                (pcgResidualPolyRec P x0 (k + 1)
                  + Polynomial.C (pcgBeta P idPrecond st) * pcgSearchPolyRec P x0 k)
                (pcgR0 P x0) := by
                simp [polyApplyLin, Module.End.mul_apply, mul_assoc]
          _ = polyApplyLin (applyALin P)
                (pcgSearchPolyRec P x0 (k + 1)) (pcgR0 P x0) := by
                simp [pcgSearchPolyRec, pcgResidualPolyRec, pcgResidualSearchPolyRec, st]
      exact ⟨hrNext, hpNext⟩

theorem pcgResidualPolyRec_eval_zero
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, (pcgResidualPolyRec P x0 k).eval 0 = 1 := by
  intro k
  induction k with
  | zero =>
      simp [pcgResidualPolyRec, pcgResidualSearchPolyRec]
  | succ k ih =>
      let st : PCGState n r := pcgRun P idPrecond x0 k
      have ih' : Polynomial.eval 0 ((pcgResidualSearchPolyRec P x0 k).1) = 1 := by
        simpa [pcgResidualPolyRec] using ih
      simp [pcgResidualPolyRec, pcgResidualSearchPolyRec, st, ih']

theorem pcgResidual_search_polyRec_natDegree_le
    (P : Problem n M r q)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat,
      (pcgResidualPolyRec P x0 k).natDegree ≤ k ∧
      (pcgSearchPolyRec P x0 k).natDegree ≤ k := by
  intro k
  induction k with
  | zero =>
      simp [pcgResidualPolyRec, pcgSearchPolyRec, pcgResidualSearchPolyRec]
  | succ k ih =>
      rcases ih with ⟨hdegR, hdegP⟩
      let st : PCGState n r := pcgRun P idPrecond x0 k
      have hdegCX : (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree ≤ 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree
              ≤ (Polynomial.C (pcgAlpha P st)).natDegree + Polynomial.X.natDegree :=
                Polynomial.natDegree_mul_le
          _ = 0 + 1 := by
                simp [Polynomial.natDegree_C, Polynomial.natDegree_X]
          _ = 1 := by simp
      have hdegCXpp :
          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree
            ≤ k + 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree
              ≤ (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree
                  + (pcgSearchPolyRec P x0 k).natDegree :=
                Polynomial.natDegree_mul_le
          _ ≤ 1 + (pcgSearchPolyRec P x0 k).natDegree := Nat.add_le_add_right hdegCX _
          _ ≤ 1 + k := Nat.add_le_add_left hdegP 1
          _ = k + 1 := by omega
      have hdegR' :
          (pcgResidualPolyRec P x0 (k + 1)).natDegree ≤ k + 1 := by
        simp [pcgResidualPolyRec, pcgResidualSearchPolyRec, st]
        calc
          (pcgResidualPolyRec P x0 k
              - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree
              ≤ max (pcgResidualPolyRec P x0 k).natDegree
                  (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree :=
                Polynomial.natDegree_sub_le _ _
          _ ≤ k + 1 := max_le (le_trans hdegR (Nat.le_succ k)) hdegCXpp
      have hdegCpp :
          (Polynomial.C (pcgBeta P idPrecond st) * pcgSearchPolyRec P x0 k).natDegree
            ≤ k + 1 := by
        calc
          (Polynomial.C (pcgBeta P idPrecond st) * pcgSearchPolyRec P x0 k).natDegree
              ≤ (pcgSearchPolyRec P x0 k).natDegree := Polynomial.natDegree_C_mul_le _ _
          _ ≤ k + 1 := le_trans hdegP (Nat.le_succ k)
      have hdegP' :
          (pcgSearchPolyRec P x0 (k + 1)).natDegree ≤ k + 1 := by
        simp [pcgSearchPolyRec, pcgResidualPolyRec, pcgResidualSearchPolyRec, st]
        calc
          ((pcgResidualPolyRec P x0 k
              - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k)
              + Polynomial.C (pcgBeta P idPrecond st) * pcgSearchPolyRec P x0 k).natDegree
              ≤ max
                  (pcgResidualPolyRec P x0 k
                    - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree
                  (Polynomial.C (pcgBeta P idPrecond st) * pcgSearchPolyRec P x0 k).natDegree :=
                Polynomial.natDegree_add_le _ _
          _ ≤ k + 1 := max_le (by
                calc
                  (pcgResidualPolyRec P x0 k
                    - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree
                      ≤ max (pcgResidualPolyRec P x0 k).natDegree
                          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgSearchPolyRec P x0 k).natDegree :=
                        Polynomial.natDegree_sub_le _ _
                  _ ≤ k + 1 := max_le (le_trans hdegR (Nat.le_succ k)) hdegCXpp
              ) hdegCpp
      exact ⟨hdegR', hdegP'⟩


end
end Q10
end AutoProof
