import autoproof.Q10.Core.KrylovAlgorithm.DefsAndPoly

set_option autoImplicit false

open scoped BigOperators Kronecker
open Matrix

namespace AutoProof
namespace Q10

noncomputable section

variable {n M r q : Nat}

/-- `A`-generated degree-`k` Krylov set from seed `v0` in a generic module. -/
def krylovSetLin {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v0 : V) (k : Nat) : Set V :=
  {v | ∃ i : Nat, i ≤ k ∧ v = (A^[i]) v0}

/-- `A`-generated degree-`k` Krylov submodule from seed `v0` in a generic module. -/
def krylovSubmoduleLin {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v0 : V) (k : Nat) : Submodule Real V :=
  Submodule.span Real (krylovSetLin A v0 k)

theorem krylovSubmoduleLin_mono
    {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v0 : V) {k j : Nat}
    (hkj : k ≤ j) :
    krylovSubmoduleLin A v0 k ≤ krylovSubmoduleLin A v0 j := by
  exact Submodule.span_mono (by
    intro x hx
    rcases hx with ⟨i, hik, rfl⟩
    exact ⟨i, le_trans hik hkj, rfl⟩)

theorem lin_mem_krylovSubmoduleLin_succ
    {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v0 : V)
    {k : Nat} {v : V}
    (hv : v ∈ krylovSubmoduleLin A v0 k) :
    A v ∈ krylovSubmoduleLin A v0 (k + 1) := by
  have hsubset :
      A '' (krylovSetLin A v0 k) ⊆ krylovSetLin A v0 (k + 1) := by
    intro y hy
    rcases hy with ⟨x, hx, rfl⟩
    rcases hx with ⟨i, hik, rfl⟩
    refine ⟨i + 1, Nat.succ_le_succ hik, ?_⟩
    simpa using (Function.iterate_succ_apply' (f := A) i v0).symm
  have hmap :
      Submodule.map A (krylovSubmoduleLin A v0 k) ≤
        krylovSubmoduleLin A v0 (k + 1) := by
    calc
      Submodule.map A (krylovSubmoduleLin A v0 k)
          = Submodule.span Real (A '' (krylovSetLin A v0 k)) := by
              simp [krylovSubmoduleLin]
      _ ≤ Submodule.span Real (krylovSetLin A v0 (k + 1)) := Submodule.span_mono hsubset
  exact hmap (by exact ⟨v, hv, rfl⟩)

theorem mem_krylovSubmoduleLin_exists_poly
    {V : Type*} [AddCommGroup V] [Module Real V]
    (A : Module.End Real V) (v0 : V)
    {k : Nat} {v : V}
    (hv : v ∈ krylovSubmoduleLin A v0 k) :
    ∃ p : Polynomial Real, v = polyApplyLin A p v0 := by
  refine Submodule.span_induction
    (s := krylovSetLin A v0 k)
    (p := fun x _ => ∃ p : Polynomial Real, x = polyApplyLin A p v0)
    ?hmem ?hzero ?hadd ?hsmul hv
  · intro x hx
    rcases hx with ⟨i, hik, rfl⟩
    refine ⟨Polynomial.X ^ i, ?_⟩
    simpa using (polyApplyLin_X_pow (A := A) (v := v0) (i := i)).symm
  · exact ⟨0, by simp [polyApplyLin]⟩
  · intro x y hx hy hxP hyP
    rcases hxP with ⟨px, rfl⟩
    rcases hyP with ⟨py, rfl⟩
    refine ⟨px + py, ?_⟩
    simp [polyApplyLin]
  · intro a x hx hxP
    rcases hxP with ⟨px, rfl⟩
    refine ⟨Polynomial.C a * px, ?_⟩
    simp [polyApplyLin, Module.End.mul_apply]

/-- Preconditioned linear operator `B = M⁻¹ ∘ A` in matrix coordinates. -/
def precondApplyALin (P : Problem n M r q)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real) :
    Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real :=
  MinvLin.comp (applyALin P)

theorem pcgRun_z_eq_Minv_r
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, (pcgRun P Minv x0 k).z = Minv ((pcgRun P Minv x0 k).r) := by
  intro k
  induction k with
  | zero =>
      simp [pcgRun, pcgInit]
  | succ k ih =>
      simp [pcgRun, pcgStep, pcgZNext]

/-- Algorithmic Krylov-subspace statement for preconditioned PCG (`z/p` form):
if `Minv` is represented by a linear map `MinvLin`, then at step `k` both
`z_k` and `p_k` lie in the degree-`k` Krylov submodule of
`B = MinvLin ∘ applyALin` generated by `z₀ = Minv r₀`. -/
theorem pcgRun_precond_z_search_mem_krylovSubmoduleLin
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X) :
    ∀ k : Nat,
      (pcgRun P Minv x0 k).z ∈
        krylovSubmoduleLin (precondApplyALin P MinvLin) (Minv (pcgR0 P x0)) k ∧
      (pcgRun P Minv x0 k).p ∈
        krylovSubmoduleLin (precondApplyALin P MinvLin) (Minv (pcgR0 P x0)) k := by
  intro k
  induction k with
  | zero =>
      refine ⟨?_, ?_⟩
      · have hz0 :
          (pcgRun P Minv x0 0).z = Minv (pcgR0 P x0) := by
            simp [pcgRun, pcgInit, pcgR0]
        rw [hz0]
        exact Submodule.subset_span ⟨0, le_rfl, by simp⟩
      · have hp0 :
          (pcgRun P Minv x0 0).p = Minv (pcgR0 P x0) := by
            simp [pcgRun, pcgInit, pcgR0]
        rw [hp0]
        exact Submodule.subset_span ⟨0, le_rfl, by simp⟩
  | succ k ih =>
      let B : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real :=
        precondApplyALin P MinvLin
      let z0 : Matrix (Fin n) (Fin r) Real := Minv (pcgR0 P x0)
      let st : PCGState n r := pcgRun P Minv x0 k
      have hzk : st.z ∈ krylovSubmoduleLin B z0 k := by simpa [st, B, z0] using ih.1
      have hpk : st.p ∈ krylovSubmoduleLin B z0 k := by simpa [st, B, z0] using ih.2
      have hzLift : st.z ∈ krylovSubmoduleLin B z0 (k + 1) :=
        krylovSubmoduleLin_mono (A := B) (v0 := z0) (hkj := Nat.le_succ k) hzk
      have hpLift : st.p ∈ krylovSubmoduleLin B z0 (k + 1) :=
        krylovSubmoduleLin_mono (A := B) (v0 := z0) (hkj := Nat.le_succ k) hpk
      have hBp : B st.p ∈ krylovSubmoduleLin B z0 (k + 1) :=
        lin_mem_krylovSubmoduleLin_succ (A := B) (v0 := z0) hpk
      have hzEqMinv : st.z = Minv st.r := by
        simpa [st] using pcgRun_z_eq_Minv_r (P := P) (Minv := Minv) (x0 := x0) k
      have hzEqLin : st.z = MinvLin st.r := by
        rw [hzEqMinv, hMinv]
      have hzNextEq :
          (pcgRun P Minv x0 (k + 1)).z
            = st.z - pcgAlpha P st • (B st.p) := by
        calc
          (pcgRun P Minv x0 (k + 1)).z
              = Minv (pcgRNext P st) := by
                  simp [pcgRun, pcgStep, pcgZNext, st]
          _ = MinvLin (pcgRNext P st) := by rw [hMinv]
          _ = MinvLin (st.r - pcgAlpha P st • pcgAp P st) := rfl
          _ = MinvLin st.r - pcgAlpha P st • MinvLin (pcgAp P st) := by
                simp [map_sub, map_smul]
          _ = st.z - pcgAlpha P st • (B st.p) := by
                simp [hzEqLin, B, precondApplyALin, pcgAp, applyALin]
      have hzNext :
          (pcgRun P Minv x0 (k + 1)).z ∈ krylovSubmoduleLin B z0 (k + 1) := by
        rw [hzNextEq]
        exact Submodule.sub_mem (krylovSubmoduleLin B z0 (k + 1)) hzLift
          (Submodule.smul_mem (krylovSubmoduleLin B z0 (k + 1)) (pcgAlpha P st) hBp)
      have hpNextEq :
          (pcgRun P Minv x0 (k + 1)).p
            = (pcgRun P Minv x0 (k + 1)).z + pcgBeta P Minv st • st.p := by
        simp [pcgRun, pcgStep, pcgPNext, pcgZNext, st]
      have hpNext :
          (pcgRun P Minv x0 (k + 1)).p ∈ krylovSubmoduleLin B z0 (k + 1) := by
        rw [hpNextEq]
        exact Submodule.add_mem (krylovSubmoduleLin B z0 (k + 1)) hzNext
          (Submodule.smul_mem (krylovSubmoduleLin B z0 (k + 1)) (pcgBeta P Minv st) hpLift)
      exact ⟨hzNext, hpNext⟩

/-- Polynomial-Krylov form for preconditioned PCG (`z/p` form):
under a linear realization of `Minv`, both `z_k` and `p_k` are generated as
`p(B) z₀` with `B = MinvLin ∘ applyALin`. -/
theorem pcgRun_precond_z_search_poly_representation
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X) :
    ∀ k : Nat, ∃ pz pp : Polynomial Real,
      (pcgRun P Minv x0 k).z
        = polyApplyLin (precondApplyALin P MinvLin) pz (Minv (pcgR0 P x0)) ∧
      (pcgRun P Minv x0 k).p
        = polyApplyLin (precondApplyALin P MinvLin) pp (Minv (pcgR0 P x0)) := by
  intro k
  have hkry :=
    pcgRun_precond_z_search_mem_krylovSubmoduleLin
      (P := P) (Minv := Minv) (MinvLin := MinvLin) (x0 := x0) hMinv k
  rcases mem_krylovSubmoduleLin_exists_poly
      (A := precondApplyALin P MinvLin)
      (v0 := Minv (pcgR0 P x0))
      (v := (pcgRun P Minv x0 k).z) hkry.1 with ⟨pz, hpz⟩
  rcases mem_krylovSubmoduleLin_exists_poly
      (A := precondApplyALin P MinvLin)
      (v0 := Minv (pcgR0 P x0))
      (v := (pcgRun P Minv x0 k).p) hkry.2 with ⟨pp, hpp⟩
  exact ⟨pz, pp, hpz, hpp⟩

/-- Canonical preconditioned residual/search polynomial recursion driven by
the concrete `pcgRun` scalars (`alpha_k`, `beta_k`). -/
def pcgPrecondResidualSearchPolyRec
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) : Nat → (Polynomial Real × Polynomial Real)
  | 0 => (1, 1)
  | k + 1 =>
      let st : PCGState n r := pcgRun P Minv x0 k
      let prev := pcgPrecondResidualSearchPolyRec P Minv x0 k
      let pzk := prev.1
      let ppk := prev.2
      let pzNext := pzk - Polynomial.C (pcgAlpha P st) * Polynomial.X * ppk
      let ppNext := pzNext + Polynomial.C (pcgBeta P Minv st) * ppk
      (pzNext, ppNext)

def pcgPrecondResidualPolyRec
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) (k : Nat) : Polynomial Real :=
  (pcgPrecondResidualSearchPolyRec P Minv x0 k).1

def pcgPrecondSearchPolyRec
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) (k : Nat) : Polynomial Real :=
  (pcgPrecondResidualSearchPolyRec P Minv x0 k).2

/-- Correctness of the canonical preconditioned polynomial recursion:
`z_k` and `p_k` are exactly the generated polynomial actions of
`B = MinvLin ∘ applyALin` on `z0 = Minv r0`. -/
theorem pcgRun_precond_z_search_polyRec_correct
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X) :
    ∀ k : Nat,
      (pcgRun P Minv x0 k).z
        = polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondResidualPolyRec P Minv x0 k) (Minv (pcgR0 P x0)) ∧
      (pcgRun P Minv x0 k).p
        = polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondSearchPolyRec P Minv x0 k) (Minv (pcgR0 P x0)) := by
  intro k
  induction k with
  | zero =>
      refine ⟨?_, ?_⟩
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, pcgPrecondResidualPolyRec,
          pcgPrecondResidualSearchPolyRec]
      · simp [pcgRun, pcgInit, pcgR0, polyApplyLin, pcgPrecondSearchPolyRec,
          pcgPrecondResidualSearchPolyRec]
  | succ k ih =>
      let B : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real :=
        precondApplyALin P MinvLin
      let z0 : Matrix (Fin n) (Fin r) Real := Minv (pcgR0 P x0)
      let st : PCGState n r := pcgRun P Minv x0 k
      have hzk : st.z = polyApplyLin B (pcgPrecondResidualPolyRec P Minv x0 k) z0 := by
        simpa [st, B, z0] using ih.1
      have hpk : st.p = polyApplyLin B (pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
        simpa [st, B, z0] using ih.2
      have hBp :
          B st.p
            = polyApplyLin B (Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
        calc
          B st.p = B (polyApplyLin B (pcgPrecondSearchPolyRec P Minv x0 k) z0) := by
            simpa [hpk]
          _ = polyApplyLin B (Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
            symm
            simp [polyApplyLin, Module.End.mul_apply]
      have hzEqMinv : st.z = Minv st.r := by
        simpa [st] using pcgRun_z_eq_Minv_r (P := P) (Minv := Minv) (x0 := x0) k
      have hzEqLin : st.z = MinvLin st.r := by
        rw [hzEqMinv, hMinv]
      have hzNext :
          (pcgRun P Minv x0 (k + 1)).z
            = polyApplyLin B (pcgPrecondResidualPolyRec P Minv x0 (k + 1)) z0 := by
        calc
          (pcgRun P Minv x0 (k + 1)).z
              = st.z - pcgAlpha P st • (B st.p) := by
                  calc
                    (pcgRun P Minv x0 (k + 1)).z
                        = Minv (pcgRNext P st) := by
                            simp [pcgRun, pcgStep, pcgZNext, st]
                    _ = MinvLin (pcgRNext P st) := by rw [hMinv]
                    _ = MinvLin (st.r - pcgAlpha P st • pcgAp P st) := rfl
                    _ = MinvLin st.r - pcgAlpha P st • MinvLin (pcgAp P st) := by
                          simp [map_sub, map_smul]
                    _ = st.z - pcgAlpha P st • (B st.p) := by
                          simp [hzEqLin, B, precondApplyALin, pcgAp, applyALin]
          _ = polyApplyLin B (pcgPrecondResidualPolyRec P Minv x0 k) z0
                - pcgAlpha P st •
                    polyApplyLin B (Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
                simp [hzk, hBp]
          _ = polyApplyLin B
                (pcgPrecondResidualPolyRec P Minv x0 k
                  - Polynomial.C (pcgAlpha P st) * Polynomial.X
                      * pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
                simp [polyApplyLin, Module.End.mul_apply, mul_assoc]
          _ = polyApplyLin B (pcgPrecondResidualPolyRec P Minv x0 (k + 1)) z0 := by
                simp [pcgPrecondResidualPolyRec, pcgPrecondSearchPolyRec,
                  pcgPrecondResidualSearchPolyRec, st]
      have hpNext :
          (pcgRun P Minv x0 (k + 1)).p
            = polyApplyLin B (pcgPrecondSearchPolyRec P Minv x0 (k + 1)) z0 := by
        calc
          (pcgRun P Minv x0 (k + 1)).p
              = pcgPNext P Minv st := by simp [pcgRun, pcgStep, st]
          _ = Minv (pcgRNext P st) + pcgBeta P Minv st • st.p := by
                simp [pcgPNext, pcgZNext]
          _ = (pcgRun P Minv x0 (k + 1)).z + pcgBeta P Minv st • st.p := by
                simp [pcgRun, pcgStep, pcgZNext, st]
          _ = polyApplyLin B (pcgPrecondResidualPolyRec P Minv x0 (k + 1)) z0
                + pcgBeta P Minv st •
                    polyApplyLin B (pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
                simp [hzNext, hpk]
          _ = polyApplyLin B
                (pcgPrecondResidualPolyRec P Minv x0 (k + 1)
                  + Polynomial.C (pcgBeta P Minv st) * pcgPrecondSearchPolyRec P Minv x0 k) z0 := by
                simp [polyApplyLin, Module.End.mul_apply, mul_assoc]
          _ = polyApplyLin B (pcgPrecondSearchPolyRec P Minv x0 (k + 1)) z0 := by
                simp [pcgPrecondSearchPolyRec, pcgPrecondResidualPolyRec,
                  pcgPrecondResidualSearchPolyRec, st]
      exact ⟨by simpa [B, z0] using hzNext, by simpa [B, z0] using hpNext⟩

theorem pcgPrecondResidualPolyRec_eval_zero
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat, (pcgPrecondResidualPolyRec P Minv x0 k).eval 0 = 1 := by
  intro k
  induction k with
  | zero =>
      simp [pcgPrecondResidualPolyRec, pcgPrecondResidualSearchPolyRec]
  | succ k ih =>
      let st : PCGState n r := pcgRun P Minv x0 k
      have ih' : Polynomial.eval 0 ((pcgPrecondResidualSearchPolyRec P Minv x0 k).1) = 1 := by
        simpa [pcgPrecondResidualPolyRec] using ih
      simp [pcgPrecondResidualPolyRec, pcgPrecondResidualSearchPolyRec, st, ih']

theorem pcgPrecondResidual_search_polyRec_natDegree_le
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real) :
    ∀ k : Nat,
      (pcgPrecondResidualPolyRec P Minv x0 k).natDegree ≤ k ∧
      (pcgPrecondSearchPolyRec P Minv x0 k).natDegree ≤ k := by
  intro k
  induction k with
  | zero =>
      simp [pcgPrecondResidualPolyRec, pcgPrecondSearchPolyRec, pcgPrecondResidualSearchPolyRec]
  | succ k ih =>
      rcases ih with ⟨hdegR, hdegP⟩
      let st : PCGState n r := pcgRun P Minv x0 k
      have hdegCX : (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree ≤ 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree
              ≤ (Polynomial.C (pcgAlpha P st)).natDegree + Polynomial.X.natDegree :=
                Polynomial.natDegree_mul_le
          _ = 0 + 1 := by
                simp [Polynomial.natDegree_C, Polynomial.natDegree_X]
          _ = 1 := by simp
      have hdegCXpp :
          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k).natDegree
            ≤ k + 1 := by
        calc
          (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k).natDegree
              ≤ (Polynomial.C (pcgAlpha P st) * Polynomial.X).natDegree
                  + (pcgPrecondSearchPolyRec P Minv x0 k).natDegree :=
                Polynomial.natDegree_mul_le
          _ ≤ 1 + (pcgPrecondSearchPolyRec P Minv x0 k).natDegree :=
                Nat.add_le_add_right hdegCX (pcgPrecondSearchPolyRec P Minv x0 k).natDegree
          _ ≤ 1 + k := Nat.add_le_add_left hdegP 1
          _ = k + 1 := by simp [Nat.add_comm, Nat.add_left_comm, Nat.add_assoc]
      have hdegPz' :
          (pcgPrecondResidualPolyRec P Minv x0 (k + 1)).natDegree ≤ k + 1 := by
        calc
          (pcgPrecondResidualPolyRec P Minv x0 (k + 1)).natDegree
              = (pcgPrecondResidualPolyRec P Minv x0 k
                  - Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k).natDegree := by
                    simp [pcgPrecondResidualPolyRec, pcgPrecondSearchPolyRec,
                      pcgPrecondResidualSearchPolyRec, st]
          _ ≤ max (pcgPrecondResidualPolyRec P Minv x0 k).natDegree
                (Polynomial.C (pcgAlpha P st) * Polynomial.X * pcgPrecondSearchPolyRec P Minv x0 k).natDegree :=
                Polynomial.natDegree_sub_le _ _
          _ ≤ k + 1 := max_le (le_trans hdegR (Nat.le_succ k)) hdegCXpp
      have hdegCpp :
          (Polynomial.C (pcgBeta P Minv st) * pcgPrecondSearchPolyRec P Minv x0 k).natDegree ≤ k + 1 := by
        calc
          (Polynomial.C (pcgBeta P Minv st) * pcgPrecondSearchPolyRec P Minv x0 k).natDegree
              ≤ (pcgPrecondSearchPolyRec P Minv x0 k).natDegree :=
                Polynomial.natDegree_C_mul_le _ _
          _ ≤ k + 1 := le_trans hdegP (Nat.le_succ k)
      have hdegPp' :
          (pcgPrecondSearchPolyRec P Minv x0 (k + 1)).natDegree ≤ k + 1 := by
        calc
          (pcgPrecondSearchPolyRec P Minv x0 (k + 1)).natDegree
              = (pcgPrecondResidualPolyRec P Minv x0 (k + 1)
                  + Polynomial.C (pcgBeta P Minv st) * pcgPrecondSearchPolyRec P Minv x0 k).natDegree := by
                    simp [pcgPrecondSearchPolyRec, pcgPrecondResidualPolyRec,
                      pcgPrecondResidualSearchPolyRec, st]
          _ ≤ max (pcgPrecondResidualPolyRec P Minv x0 (k + 1)).natDegree
                (Polynomial.C (pcgBeta P Minv st) * pcgPrecondSearchPolyRec P Minv x0 k).natDegree :=
                Polynomial.natDegree_add_le _ _
          _ ≤ k + 1 := max_le hdegPz' hdegCpp
      exact ⟨hdegPz', hdegPp'⟩

/-- Preconditioned polynomial package from `pcgRun` itself:
explicit recursive residual/search polynomials over
`B = MinvLin ∘ applyALin`, with `pz_k(0)=1` and degree bounds. -/
theorem pcgRun_precond_z_search_polyRec_evalZero_deg
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X) :
    ∀ k : Nat,
      (pcgRun P Minv x0 k).z
        = polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondResidualPolyRec P Minv x0 k) (Minv (pcgR0 P x0)) ∧
      (pcgRun P Minv x0 k).p
        = polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondSearchPolyRec P Minv x0 k) (Minv (pcgR0 P x0)) ∧
      (pcgPrecondResidualPolyRec P Minv x0 k).eval 0 = 1 ∧
      (pcgPrecondResidualPolyRec P Minv x0 k).natDegree ≤ k ∧
      (pcgPrecondSearchPolyRec P Minv x0 k).natDegree ≤ k := by
  intro k
  have hCorr :=
    pcgRun_precond_z_search_polyRec_correct
      (P := P) (Minv := Minv) (MinvLin := MinvLin) (x0 := x0) hMinv k
  have hEval := pcgPrecondResidualPolyRec_eval_zero (P := P) (Minv := Minv) (x0 := x0) k
  have hDeg := pcgPrecondResidual_search_polyRec_natDegree_le (P := P) (Minv := Minv) (x0 := x0) k
  exact ⟨hCorr.1, hCorr.2, hEval, hDeg.1, hDeg.2⟩

/-- Residual reconstruction from the preconditioned polynomial recursion:
if `MinvInv ∘ Minv = id`, then the concrete residual equals
`MinvInv (pz_k(B) z0)`. -/
theorem pcgRun_precond_residual_eq_leftInverse_polyRec
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (MinvInv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X)
    (hLeftInv : ∀ X : Matrix (Fin n) (Fin r) Real, MinvInv (Minv X) = X) :
    ∀ k : Nat,
      (pcgRun P Minv x0 k).r
        = MinvInv (polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondResidualPolyRec P Minv x0 k) (Minv (pcgR0 P x0))) := by
  intro k
  have hzPoly :=
    (pcgRun_precond_z_search_polyRec_correct
      (P := P) (Minv := Minv) (MinvLin := MinvLin) (x0 := x0) hMinv k).1
  have hzEq : (pcgRun P Minv x0 k).z = Minv ((pcgRun P Minv x0 k).r) := by
    simpa using pcgRun_z_eq_Minv_r (P := P) (Minv := Minv) (x0 := x0) k
  calc
    (pcgRun P Minv x0 k).r = MinvInv (Minv ((pcgRun P Minv x0 k).r)) := by
      symm
      exact hLeftInv ((pcgRun P Minv x0 k).r)
    _ = MinvInv ((pcgRun P Minv x0 k).z) := by rw [hzEq]
    _ = MinvInv (polyApplyLin (precondApplyALin P MinvLin)
          (pcgPrecondResidualPolyRec P Minv x0 k) (Minv (pcgR0 P x0))) := by
          rw [hzPoly]

/-- Norm bridge from preconditioned polynomial residual expression to the
concrete residual norm, under a left-inverse stability bound. -/
theorem pcgRun_precond_residual_norm_le_leftInverse_polyRec
    (P : Problem n M r q)
    (Minv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (MinvLin : Matrix (Fin n) (Fin r) Real →ₗ[Real] Matrix (Fin n) (Fin r) Real)
    (MinvInv : Matrix (Fin n) (Fin r) Real → Matrix (Fin n) (Fin r) Real)
    (x0 : Matrix (Fin n) (Fin r) Real)
    (hMinv : ∀ X : Matrix (Fin n) (Fin r) Real, Minv X = MinvLin X)
    (hLeftInv : ∀ X : Matrix (Fin n) (Fin r) Real, MinvInv (Minv X) = X)
    {c : Real}
    (hInvBound : ∀ X : Matrix (Fin n) (Fin r) Real,
      ‖(MinvInv X).vec‖ ≤ c * ‖X.vec‖) :
    ∀ k : Nat,
      ‖(pcgRun P Minv x0 k).r.vec‖
        ≤ c * ‖(polyApplyLin (precondApplyALin P MinvLin)
            (pcgPrecondResidualPolyRec P Minv x0 k) (Minv (pcgR0 P x0))).vec‖ := by
  intro k
  rw [pcgRun_precond_residual_eq_leftInverse_polyRec
    (P := P) (Minv := Minv) (MinvLin := MinvLin) (MinvInv := MinvInv)
    (x0 := x0) (hMinv := hMinv) (hLeftInv := hLeftInv) k]
  exact hInvBound _

end
end Q10
end AutoProof
